### ISSUE TITLE
2v VCA production files

### ISSUE THREAD

**Issue by blambo1** [forestcaver/Analog-Voice#2] opened 2022-02-26 00:37 UTC
Hi, I've successfully printed and built a couple of these modules and they're great! I'm trying to order the 2v VCA through JLCPCB and stuck. I'm pretty new and not super familiar with KiCad, when I import I get errors and the layout is pretty awful- in order to print and have usable boards I'll need to individually adjust the placement of each label, at minimum. Can you upload the ZIP fabrication files for the main board as you have for other modules and for the panels to this module?

**Comment by forestcaver** [comment] 2022-02-26 11:44
As Olly says - use Eagle! You can generate your own gerbers - I didnt add gerbers deliberately - for my builds I use a very minimal silkscreen and have had complaints from people saying they didnt like it so I stopped uploading the zipped gerbers. All the data is there for people to have as complex and detailed a silkscreen as they like…
Closing this as it’s not a bug…

**Closed by forestcaver** 2022-02-26 11:44 UTC
